# Generated by Django 4.2.30 on 2026-04-21 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Name of the real estate project', max_length=200)),
                ('location', models.CharField(blank=True, help_text='City / area', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market_score', models.FloatField(help_text='Market attractiveness score (0–100)')),
                ('property_score', models.FloatField(help_text='Property quality score (0–100)')),
                ('builder_score', models.FloatField(help_text='Builder credibility score (0–100)')),
                ('financial_score', models.FloatField(help_text='Financial health score (0–100)')),
                ('is_publicly_listed', models.BooleanField(default=False, help_text='Is builder listed on stock exchange?')),
                ('net_worth_crores', models.FloatField(help_text='Builder net worth (₹ Crores)')),
                ('projects_completed', models.PositiveIntegerField(help_text='Number of projects completed')),
                ('builder_years_in_business', models.PositiveIntegerField(help_text='Years builder has been in business')),
                ('litigation_count', models.PositiveIntegerField(help_text='Number of active litigations')),
                ('rera_violations', models.PositiveIntegerField(help_text='Number of RERA violations')),
                ('avg_delay_months', models.FloatField(help_text='Average project delay (months)')),
                ('debt_to_equity_ratio', models.FloatField(help_text='Builder debt-to-equity ratio')),
                ('loan_to_value_pct', models.FloatField(help_text='Loan-to-value percentage (%)')),
                ('price_cagr_3yr', models.FloatField(help_text='3-year price CAGR (%)')),
                ('expected_rental_yield', models.FloatField(help_text='Expected rental yield (%)')),
                ('monthly_absorption_pct', models.FloatField(help_text='Monthly absorption rate (%)')),
                ('inventory_months', models.FloatField(help_text='Inventory overhang (months)')),
                ('new_supply_units', models.PositiveIntegerField(help_text='New supply units in micro-market')),
                ('distance_to_cbd_km', models.FloatField(help_text='Distance to Central Business District (km)')),
                ('distance_to_metro_km', models.FloatField(help_text='Distance to nearest metro station (km)')),
                ('predicted_score', models.FloatField(blank=True, null=True)),
                ('risk_category', models.CharField(blank=True, choices=[('Low Risk', 'Low Risk'), ('Moderate Risk', 'Moderate Risk'), ('Medium Risk', 'Medium Risk'), ('High Risk', 'High Risk'), ('Very High Risk', 'Very High Risk')], default='', max_length=20)),
                ('recommendation', models.CharField(blank=True, choices=[('INVEST', 'INVEST'), ('HOLD', 'HOLD'), ('AVOID', 'AVOID')], default='', max_length=10)),
                ('confidence_level', models.CharField(blank=True, choices=[('High Confidence', 'High Confidence'), ('Medium Confidence', 'Medium Confidence'), ('Low Confidence', 'Low Confidence')], default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Property Assessment',
                'verbose_name_plural': 'Property Assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
